"""customer constraint

Revision ID: 441ae95ade8a
Revises: 92418c921c09
Create Date: 2026-01-08 20:39:20.720877

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa  # noqa


# revision identifiers, used by Alembic.
revision: str = "441ae95ade8a"
down_revision: Union[str, Sequence[str], None] = "92418c921c09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_user_email", "customers", ["user_id", "email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_email", "customers", type_="unique")
    # ### end Alembic commands ###
