"""initial tables

Revision ID: fb0beba99ef5
Revises: 
Create Date: 2026-01-08 16:21:21.649563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb0beba99ef5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'metrics', ['id'])
    op.add_column('task', sa.Column('task_id', sa.Integer(), nullable=False))
    op.add_column('task', sa.Column('file_name', sa.String(), nullable=False))
    op.drop_index(op.f('ix_task_taskId'), table_name='task')
    op.create_index(op.f('ix_task_task_id'), 'task', ['task_id'], unique=True)
    op.drop_column('task', 'taskId')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('taskId', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_task_task_id'), table_name='task')
    op.create_index(op.f('ix_task_taskId'), 'task', ['taskId'], unique=True)
    op.drop_column('task', 'file_name')
    op.drop_column('task', 'task_id')
    op.drop_constraint(None, 'metrics', type_='unique')
    # ### end Alembic commands ###
